User/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import PasswordResetMPSEmailView, SignUpView, edit_profile, contact
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView,\
    PasswordResetDoneView, PasswordResetConfirmView
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path('change-password/', PasswordChangeView.as_view(), name='password_change'),
    path('change-password-done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset-form/', PasswordResetMPSEmailView.as_view(), name='password_reset_form'),
    path('password-reset-done-form/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('review/', views.contact, name='review'),
    path('review_thankyou/', TemplateView.as_view(template_name='review_thankyou.html'), name='review_thankyou'),
    path('classes/', login_required(TemplateView.as_view( template_name='classes.html')), name='classes'),
    path('profile_preview/', TemplateView.as_view(template_name='profile_preview.html'), name='profile_preview'),
    path('profile/', views.edit_profile, name='profile'),
    path('hobby_list/', login_required(views.hobby_list), name='hobby_list'),
    path('online_hobby_list/', login_required(views.online_hobby_list), name='online_hobby_list'),
    path('online_hobby_video_page/<int:pk>/', login_required(views.online_onclick_getstarted), name='online_class_video_page'),
    path('online_hobby_enroll/<int:pk>/', login_required(views.online_class_enroll), name='online_class_enroll'),
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', views.order_details, name="order_summary"),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', views.delete_from_cart, name='delete_item'),
    url(r'^order_confirm/$', views.order_confirm, name="order_checkout"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

time_for_skill/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
                  path('admin/', admin.site.urls),
                  path('User/', include('User.urls')),
                  path('User/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('OnlineHobbies/', include('OnlineHobbies.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models
from Hobbies.models import Inclass
from User.models import User


class CartItem(models.Model):
    classes = models.OneToOneField(Inclass, on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.classes.class_name


class Cart(models.Model):
    ref_code = models.CharField(max_length=15)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(CartItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def __str__(self):
        return '{0}'.format(self.user)

templates/about.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>About us</title>
</head>
{% block content %}
<body>
<div class="box1">
    <p> Welcome to TIME FOR SKILL</p>>
    <p>Here people can learn and improve their hobbies. If you are not a member, you can sign up today


    <h3>Come and Join the fun. Subscribe Here !</h3>
    <form action="{% url 'subscribe' %}" method="post" >


{% endblock content %}
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <title>Time For Skill</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="{% static "Hobbies/CSS/mpsmain.css" %}">
      <style>

body {
  background-color: lightblue;
}
</style>


      <style>
@font-face {
   font-family: myFirstFont;
   src: url(sansation_light.woff);
}

{
   font-family: myFirstFont;
}
</style>

  </head>

  <body>
  <div class="navbar ">
{#    <div class="container-fluid">#}
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar" id="buttonFont">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'home' %}" class="active" >Home</a></li> <!-- href Home -->
                <li><div class="dropdown">
                    <button class="dropbtn">
                        <a href="{% url 'classes' %}"><span class="word_style">Classes</span></a>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'online_hobby_list' %}">Online</a>
                        <a href="{% url 'hobby_list' %}">In class</a>
                    </div>
                    </div>
                </li>  <!-- changed to classes -->
           </ul>
            <ul class="nav navbar-nav navbar-right">

                     {% if user.is_authenticated %}
                        <li class="nav-item">
                      <a class=" " href="#" id="userMenu"\
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded\
                      ="false">
                       Hi {{ user.username }} <br> {% if user.user_type == 2 %} (Instructor) {%  else %} (User) {% endif %}, <span class="caret"></span>
                      </a>
                      <div class="dropdown-menu dropdown-menu-right"
                      aria-labelledby="userMenu">
                          <a class="dropdown-item" href="{% url 'profile_preview' %}">
                        My Profile</a>
                          <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'password_change'%}">
                            Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                        Log Out</a>
                          <div class="dropdown-divider"></div>

                      </div>
                    </li>
                    {%  else %}
                    <li><a href="{% url 'signup' %}" >Signup</a></li>
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in" style="height: 50%"></span> Login</a></li>

                    {% endif %}
                    {#   add count of items added for the cart button - Apr 9 2020 #}
                    <li><a href="{% url 'order_summary' %}"><span class="glyphicon glyphicon-shopping-cart"></span> <sup>{{ user.cart_set.all.first.items.all|length }}</sup>Cart</a> </li>
            </ul>
        </div>
  </div>
{#  </div>#}
  </nav>

    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </body>

<footer class="footer mt-auto py-3">
  <div class="container">

  </div>
</footer>
</html>

templates/classes.html
<!DOCTYPE html>
<html>
{% extends 'base.html' %}
{% load static %}

  {% block content %}

		<br>
		<br>
		<div class="box">
			<h3>Photography</h3>
			<p>the art or practice of taking and processing photographs.
			</p>
		</div>
		<br>
	    <div class="box">
			<h3>craftworks</h3>
			<p>
                Craftworks means making of things, especially decorative objects, by hand as a profession or leisure activity.
			</p>
		</div>
		<br>
		<div class="box">
			<h3>Baking</h3>
			<p>cook (food) by dry heat without direct exposure to a flame, typically in an oven or on a hot surface.
              "they bake their own bread and cakes"
            </p>
		</div>
		<br>
		<div class="box">
			<h3>Painting</h3>
			<p>
              the process or art of using paint, in a picture, as a protective coating, or as decoration.
			</p>
		</div>
		<br>
		<div class="box">
			<h3>Dance</h3>
			<p>move rhythmically to music, typically following a set sequence of steps.
			</p>
		</div>
		<br>
		<div class="box">
			<h3>Music</h3>
			<p>
                vocal or instrumental sounds (or both) combined in such a way as to produce beauty of form, harmony, and expression of emotion.
			</p>
		</div>

  {% endblock content %}
</html>

templates/hobby_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>list</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
{% block content %}
    <br>
    <br>

   <div>
        <table class="table table-unbordered table-hover">
            {% for Hobby in Hobbies %}
                <tr>
                    <td>
                        <img src = "{{Hobby.image.url}}" id="inclasspics" alt={{ Hobby.class_name }}/>
                        <br>
                        <h3>
                            {{ Hobby.class_name }}
                        </h3>
                        <br>
                        <h4>
                            {{ Hobby.short_description }}
                        </h4>
                        <br>
                        <p>
                            {{ Hobby.description }}
                        </p>
                        <br>This class is available from
                        <a class="warning">{{ Hobby.created_date }}     </a> <a href="{% url 'add_to_cart' Hobby.class_name %}" id="addcart" onclick="return alert('Class successfully added to the cart!')" class="btn btn-warning">Add to cart</a>
                    </td>
                </tr>
            {% endfor %}
        </table>


    </div>
{% endblock content %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load static %}

<head>
  <title>Time For Learn Home</title>
</head>
{% block content %}

    <h1>TIME FOR SKILL</h1>
  {% endblock content %}
</body>
</html>

templates/online_hobby_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load static %}
{#this is to add filter function in html template for user enrollment purpose Apr 9 2020#}
{% load mps_extras %}


<head>
    <meta charset="UTF-8">
    <title>list</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
{% block content %}
    <br>
    <br>
    {#    this is to give messages when user is enrolled to a class - Apr 9 2020#}
    <div class="container">
        <table class="table table-unbordered table-hover">
            <tbody>
            {# if there are no online hobbies created by admin or instructor-- Apr 9 2020 #}
            {% if not OnlineHobbies %}
                No Online classes are currently available.
            {% else %}
                {#if online hoobies are present - Apr 9 2020 #}
                {% for OnlineHobby in OnlineHobbies %}
                    <tr>
                        <td>
                            <img src="{{ OnlineHobby.image.url }}" class="img-rounded img-responsive" id="onlinepics"
                                 style="width: 30%"
                                 alt={{ OnlineHobby.online_class_name }}><br>
                            <h3>{{ OnlineHobby.online_class_name }}</h3>
                            <h4> {{ OnlineHobby.description }}</h4>
                            <br>
                            {% for enrollment in OnlineHobby.OnlineClassEnroll.all|for_user:user %}

                               {# check enrollment status of that user, if enrolled - Apr 9 2020 #}
                                {% if enrollment.enrollment_status %}
                                    <a href="{% url 'online_class_video_page' OnlineHobby.id %}"
                                       class="btn btn-warning">Get Started</a>
                                {% else %}
                                {#     if user is not enrolled  - Apr 9 2020 #}
                                    <a href="{% url 'online_class_enroll' OnlineHobby.id %}"
                                       onclick="return confirm('Are you sure you want to Enroll?')"
                                       class="btn btn-warning">Enroll</a>
                                {% endif %}
                            {% endfor %}
                            {% if not OnlineHobby.OnlineClassEnroll.all|for_user:user %}
                                <a href="{% url 'online_class_enroll' OnlineHobby.id %}"
                                       onclick="return confirm('Are you sure you want to Enroll?')"
                                       class="btn btn-warning">Enroll</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
{% endblock content %}
</body>
</html>

templates/onlineclassesbase.html
{% extends 'base.html' %}
{% load static %}
{#this template tags helps to give list of details for videolinks and class requirements - Apr 9 2020 #}
{% load mps_extras %}
<div class="container-basevideo">
  {% block content %}
        <h1 id="thead">{{ onlineclassvideos.class_title }}</h1>
        <h2>{{ onlineclassvideos.class_subtitle }}</h2>
        <h3>Requirements</h3>
        {# provide class requirements in list - Apr 9 2020 #}
        {% with onlineclassvideos.class_requirements|split:"." as class_requirements_list %}
            {% for classrqts in class_requirements_list %}
                <li>{{ classrqts }}</li>
            {% endfor %}
        {% endwith %}
        <h3>What you'll learn</h3>
        <p>{{ onlineclassvideos.class_goal }}</p>

      <p>More information can be found in <cite><q>https://www.udemy.com/course/photography-masterclass-complete-guide-to-photography</q></cite>.</p>
        <h2>Learn {{ onlineclassvideos.online_class_name }} : </h2>
        {# this splits video links so that it will display lesson1 video - Apr 9 2020  #}
        {% with onlineclassvideos.class_video_links|split:"," as class_video_links_list %}
            <div class="embed-responsive-1by1">
                <iframe class="embed-responsive-item-1" id="vid_frame"
                        src="https://www.youtube.com/embed/v/{{ class_video_links_list.0 }}?version=3&loop=1&playlist={{ class_video_links_list.0 }}"
                        frameborder="0" allowfullscreen></iframe>
            </div>
        {# Display Video lessons as sub items - Apr 9 2020   #}
         {% for classVideos in class_video_links_list %}
                <div class="vid-list-1">
                    <div class="vid-item-1"
                         onClick="document.getElementById('vid_frame').src='http://youtube.com/embed/{{ classVideos }}?autoplay=1&rel=0&showinfo=0&autohide=1'">
                        <div class="thumb-1">
                            <img id="link-thumbnail" src="http://img.youtube.com/vi/{{ classVideos }}/0.jpg"
                                 alt="lesson1"/>
                        </div>
                        <div class="desc">
                            Lesson {{ forloop.counter }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endwith %}
    {% endblock content %}
</div>

templates/order_confirm.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{% block content %}
<h2>Thank you </h2>
    <p>Thank you for your reservation!.Please check your email with which you have registered with us for further details</p>

{% endblock content %}
</html>

templates/order_summary.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>list</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
    <body>
        {% block content %}
        <br>
        <br>
            {#   This is added here to display messages whether item added to cart or not April 9 2020 #}
      {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
        <section>
            <div class="row">
                <table class="table table-unbordered table-hover">
                    {% for item in order.get_cart_items %}
                        <tr>
                            <td>
                                <img src = "{{item.classes.image.url}}" id="inclasspics" alt={{ item.classes.class_name }}/>
                                <br>
                                <h3>
                                    {{ item.classes.class_name }}
                                </h3>
                                <br>
                                <h4>
                                    {{ item.classes.short_description }}
                                </h4>
                                <br>
                                <form action="{% url 'delete_item' item.id %}" method="post">
                                    <input onclick="return confirm('Do you want to remove this item from cart?')" class="btn btn-warning" type="submit" value="Remove">
                                    {% csrf_token %}
                                </form>
                                <br>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan= 3> You have not added any items yet.</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan=1 >
                            <p class="text-right">
                                <a href="{% url 'hobby_list' %}" class="btn btn-warning">
                                    Continue Shopping
                                </a>
                                {% if order.get_cart_items %}
                                <a href="{% url 'order_checkout' %}" class="btn btn-warning">
                                    Checkout
                                </a>
                                {% endif %}
                            </p>
                        </td>
                    </tr>
                </table>
            </div>
        </section>
        {% endblock %}
    </body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
{% block content %}
    <h1>Edit Profile</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

</html>

templates/profile_preview.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<body>

<div class="row">
    <h3 style="font-weight: inherit">My Profile</h3>
</div>
<br/>
<div class="form-row row mb-4 mt-4">
    <div class="info-wrapper">
        <div class="col-sm-2 col-form-label info"> Username:</div>
        <div class="col-sm-4">{{ user.username }}</div>
    </div>
</div>
<br/>
<div class="form-row row mb-4 mt-4">
    <div class="info-wrapper">
        <div class="col-sm-2 col-form-label info"> Email:</div>
        <div class="col-sm-4">{{ user.email }}</div>
    </div>
</div>
<br/>
<div class="form-row row mb-4 mt-4">
    <div class="info-wrapper">
        <div class="col-sm-2 col-form-label info"> Phone:</div>
        <div class="col-sm-4">{{ user.cell_phone }}</div>
    </div>
</div>
<br>
<div class="col-sm-2">
    <a class="btn btn-default" href="{% url 'profile' %}">
                        Edit My Profile</a>
</div>
</body>
{% endblock content %}
</html>

templates/signup.html
<!doctype html>
<html lang="en">
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>
{% endblock content %}
</html>